/**
 * supportV8 Seed Database & In-Memory Store
 * Production-ready mock data matching supportV8 design specification v0.3
 */

import type {
  Issue,
  Problem,
  Insight,
  KnowledgeArticle,
  KnowledgeGap,
  KnowledgeProposal,
  KnowledgeDocument,
  KnowledgeDocumentChunk,
  KnowledgeWebSource,
  StaleWorkCandidate,
  SourceConnector,
  SupportPolicy,
  OverviewMetrics,
  TenantConfig,
} from "../types";

export const DEFAULT_TENANT: TenantConfig = {
  tenantId: "tenant_default",
  name: "Acme Cloud Services",
  mode: "autonomous",
  featureFlags: {
    observeMode: true,
    copilotMode: true,
    autonomousMode: true,
    problemCorrelation: true,
    businessImpact: true,
    knowledgeIntelligence: true,
    proactiveComms: true,
    staleWorkSweep: true,
  },
};

export const INITIAL_SOURCES: SourceConnector[] = [
  {
    id: "src_zd_01",
    name: "Primary Zendesk Instance",
    type: "zendesk",
    status: "connected",
    lastSync: "2 mins ago",
    eventCountToday: 1420,
    credentialsConfigured: true,
    endpointUrl: "https://acme.zendesk.com/api/v2",
    capabilities: {
      read: ["tickets", "comments", "users", "tags", "custom_fields"],
      realtime: ["ticket.created", "ticket.updated", "comment.added"],
      write: ["add_tag", "update_priority", "add_internal_note", "close_ticket"],
    },
  },
  {
    id: "src_ic_01",
    name: "In-App Intercom Messenger",
    type: "intercom",
    status: "connected",
    lastSync: "Just now",
    eventCountToday: 890,
    credentialsConfigured: true,
    endpointUrl: "https://api.intercom.io/conversations",
    capabilities: {
      read: ["conversations", "contacts", "tags"],
      realtime: ["conversation.user.created", "conversation.user.replied"],
      write: ["tag_conversation", "assign_team", "send_reply"],
    },
  },
  {
    id: "src_tw_01",
    name: "Twilio Voice Contact Center",
    type: "twilio_voice",
    status: "connected",
    lastSync: "5 mins ago",
    eventCountToday: 310,
    credentialsConfigured: true,
    endpointUrl: "wss://stream.twilio.com/v1/voice",
    capabilities: {
      read: ["call_metadata", "realtime_transcripts"],
      realtime: ["call.started", "call.transcription", "call.ended"],
      write: ["transfer_call", "trigger_sms_followup"],
    },
  },
  {
    id: "src_kb_01",
    name: "KnowledgeV8 Corporate Base",
    type: "knowledgev8",
    status: "connected",
    lastSync: "1 hour ago",
    eventCountToday: 54,
    credentialsConfigured: true,
    endpointUrl: "https://knowledge.servicev8.internal/api",
    capabilities: {
      read: ["search_articles", "fetch_content", "analytics"],
      realtime: ["article.updated"],
      write: ["publish_article", "create_draft", "deprecate_article"],
    },
  },
];

export const INITIAL_PROBLEMS: Problem[] = [
  {
    id: "PRB-218",
    tenantId: "tenant_default",
    title: "Payment Gateway 504 Gateway Timeout During Checkout",
    summary: "High failure rate on Stripe v3 3DS verification webhook causing cart freezes during payment submission.",
    suspectedCause: "Upstream gateway API latency exceeding 8000ms timeout threshold in checkout worker v4.18.",
    status: "active",
    confidence: 0.94,
    impact: "critical",
    affectedCustomerCount: 187,
    affectedEnterpriseCount: 7,
    linkedIssueIds: ["ISS-1001", "ISS-1002", "ISS-1005", "ISS-1011"],
    estimatedRevenueExposure: 126000,
    firstSeen: "2026-08-26T02:15:00Z",
    lastSeen: "2026-08-26T04:45:00Z",
    trend: "increasing",
    owner: "Incident AI Employee / FinTech Ops",
    recommendedActions: [
      "Switch checkout worker fallback to Secondary Adyen Gateway",
      "Broadcast proactive status notification to 187 affected checkout sessions",
      "Apply Action Gateway policy override to auto-refund double-charge transactions",
    ],
    communicationsCount: 1,
    verificationState: "in_progress",
    sourceSystems: ["zendesk", "intercom", "chat"],
  },
  {
    id: "PRB-219",
    tenantId: "tenant_default",
    title: "Okta SAML 2.0 Identity Assertion Failure on Enterprise Login",
    summary: "Users from domain *.nordicenterprises.com unable to authenticate via Single Sign-On after certificate rotation.",
    suspectedCause: "Mismatch in X.509 signing certificate fingerprint in Identity Federation metadata.",
    status: "mitigating",
    confidence: 0.91,
    impact: "high",
    affectedCustomerCount: 64,
    affectedEnterpriseCount: 3,
    linkedIssueIds: ["ISS-1003", "ISS-1007"],
    estimatedRevenueExposure: 45000,
    firstSeen: "2026-08-26T01:30:00Z",
    lastSeen: "2026-08-26T04:20:00Z",
    trend: "decreasing",
    owner: "Identity Security Team",
    recommendedActions: [
      "Resync IdP metadata in Dominion SSO manager",
      "Dispatch temporary bypass token to authorized security contacts",
    ],
    communicationsCount: 2,
    verificationState: "verified",
    sourceSystems: ["zendesk", "email"],
  },
  {
    id: "PRB-220",
    tenantId: "tenant_default",
    title: "MFA SMS Delivery Latency in EMEA Region",
    summary: "Carriers in DE and FR experiencing 15+ minute delivery delays for one-time verification passcodes.",
    suspectedCause: "Regional aggregator routing throttle during maintenance window.",
    status: "active",
    confidence: 0.88,
    impact: "medium",
    affectedCustomerCount: 42,
    affectedEnterpriseCount: 0,
    linkedIssueIds: ["ISS-1004", "ISS-1008"],
    estimatedRevenueExposure: 12000,
    firstSeen: "2026-08-26T03:00:00Z",
    lastSeen: "2026-08-26T04:40:00Z",
    trend: "stable",
    owner: "Telephony Employee",
    recommendedActions: [
      "Prompt users to switch to TOTP Authenticator App in Web UI",
      "Route SMS traffic via backup Twilio route",
    ],
    communicationsCount: 0,
    verificationState: "unverified",
    sourceSystems: ["twilio_voice", "zendesk"],
  },
];

export const INITIAL_ISSUES: Issue[] = [
  {
    id: "ISS-1001",
    tenantId: "tenant_default",
    source: "zendesk",
    externalId: "ZD-884233",
    sourceUrl: "https://acme.zendesk.com/agent/tickets/884233",
    customerRef: "C-1920",
    customerName: "Sarah Jenkins",
    customerTier: "enterprise",
    summary: "Credit card page freezes on checkout submission with spinner",
    category: "checkout_failure",
    product: "Checkout Web",
    version: "4.18.2",
    sentiment: "angry",
    sentimentScore: -0.85,
    sentimentTrajectory: "deteriorating",
    priority: "urgent",
    confidence: 0.96,
    businessImpact: "critical",
    problemId: "PRB-218",
    sourceStatus: "open",
    resolutionRiskScore: 0.88,
    recommendedAction: "Apply automated gateway mitigation note and assign to High Priority Tier",
    tags: ["checkout", "payment_timeout", "enterprise", "stripe_error"],
    createdAt: "2026-08-26T04:12:00Z",
    updatedAt: "2026-08-26T04:30:00Z",
  },
  {
    id: "ISS-1002",
    tenantId: "tenant_default",
    source: "intercom",
    externalId: "IC-554192",
    sourceUrl: "https://app.intercom.com/a/apps/acme/conversations/554192",
    customerRef: "C-4481",
    customerName: "David Miller",
    customerTier: "pro",
    summary: "Payment will not complete, getting error 504 repeatedly",
    category: "checkout_failure",
    product: "Checkout Web",
    version: "4.18.2",
    sentiment: "frustrated",
    sentimentScore: -0.65,
    sentimentTrajectory: "stable",
    priority: "high",
    confidence: 0.94,
    businessImpact: "high",
    problemId: "PRB-218",
    sourceStatus: "open",
    resolutionRiskScore: 0.62,
    recommendedAction: "Send automated workaround instructions for alternative payment method",
    tags: ["checkout", "error_504", "pro_tier"],
    createdAt: "2026-08-26T04:18:00Z",
    updatedAt: "2026-08-26T04:22:00Z",
  },
  {
    id: "ISS-1003",
    tenantId: "tenant_default",
    source: "zendesk",
    externalId: "ZD-884240",
    sourceUrl: "https://acme.zendesk.com/agent/tickets/884240",
    customerRef: "C-8821",
    customerName: "Michael Chang",
    customerTier: "enterprise",
    summary: "Nordic Enterprises entire engineering team locked out of SSO login",
    category: "auth_sso",
    product: "Identity / SSO",
    version: "2.4.0",
    sentiment: "urgent",
    sentimentScore: -0.9,
    sentimentTrajectory: "stable",
    priority: "urgent",
    confidence: 0.95,
    businessImpact: "critical",
    problemId: "PRB-219",
    sourceStatus: "open",
    resolutionRiskScore: 0.92,
    recommendedAction: "Generate temporary emergency login tokens and notify IT Admin",
    tags: ["sso", "saml", "okta", "enterprise_impact"],
    createdAt: "2026-08-26T03:45:00Z",
    updatedAt: "2026-08-26T04:10:00Z",
  },
  {
    id: "ISS-1004",
    tenantId: "tenant_default",
    source: "twilio_voice",
    externalId: "TW-99321",
    sourceUrl: "https://console.twilio.com/voice/calls/TW-99321",
    customerRef: "C-3310",
    customerName: "Elena Rostova",
    customerTier: "standard",
    summary: "Customer waiting 20 minutes for 2FA SMS code in Germany",
    category: "mfa_sms",
    product: "Authentication",
    version: "2.4.0",
    sentiment: "frustrated",
    sentimentScore: -0.55,
    sentimentTrajectory: "stable",
    priority: "normal",
    confidence: 0.89,
    businessImpact: "medium",
    problemId: "PRB-220",
    sourceStatus: "open",
    resolutionRiskScore: 0.45,
    recommendedAction: "Advise switching to Authenticator App or voice call code",
    tags: ["mfa", "sms_delay", "emea"],
    createdAt: "2026-08-26T03:50:00Z",
    updatedAt: "2026-08-26T04:05:00Z",
  },
  {
    id: "ISS-1005",
    tenantId: "tenant_default",
    source: "chat",
    externalId: "CH-12093",
    sourceUrl: "https://support.acme.com/live/12093",
    customerRef: "C-9104",
    customerName: "Robert Vance",
    customerTier: "enterprise",
    summary: "Tried to purchase annual enterprise plan 3 times, transaction failed",
    category: "checkout_failure",
    product: "Checkout Web",
    version: "4.18.2",
    sentiment: "angry",
    sentimentScore: -0.88,
    sentimentTrajectory: "deteriorating",
    priority: "urgent",
    confidence: 0.97,
    businessImpact: "critical",
    problemId: "PRB-218",
    sourceStatus: "open",
    resolutionRiskScore: 0.85,
    recommendedAction: "Escalate to Account Executive and offer manual invoice billing",
    tags: ["annual_contract", "checkout_fail", "high_arr"],
    createdAt: "2026-08-26T04:25:00Z",
    updatedAt: "2026-08-26T04:42:00Z",
  },
];

export const INITIAL_INSIGHTS: Insight[] = [
  {
    id: "INS-301",
    tenantId: "tenant_default",
    title: "Billing CSAT declined from 94% to 82% over the last 7 days",
    finding: "73% of negative sentiment is driven by autonomous refund delays where AI confidence fell below 75%.",
    evidence: [
      "43 customer conversations re-opened after AI refusal to refund",
      "Average CSAT on autonomous refund requests: 2.8 / 5.0",
      "Refund requests involving currency conversion show 3.2x higher failure rate",
    ],
    confidence: 0.92,
    affectedSegment: "Pro & Standard Customers (Self-Serve)",
    businessImpact: "high",
    likelyDriver: "Autonomous refund confidence threshold (72%) is triggering too many agent escalations for small balances.",
    recommendation: "Increase autonomous refund confidence threshold from 72% to 85% and auto-approve refunds < $50 for Pro accounts.",
    recommendedOperation: "zendesk.ticket.update_priority",
    status: "new",
    createdAt: "2026-08-26T02:00:00Z",
  },
  {
    id: "INS-302",
    tenantId: "tenant_default",
    title: "Sharp 217% surge in MFA authentication inquiries",
    finding: "Customers migrating to OAuth 2.0 cannot find instructions for TOTP hardware key enrollment.",
    evidence: [
      "86 tickets opened in 48 hours referencing 'YubiKey' or 'FIDO2'",
      "Knowledge search queries for 'Hardware Key' returned 0 matching articles",
      "Average agent handling time on these cases is 22 minutes",
    ],
    confidence: 0.95,
    affectedSegment: "Enterprise IT Administrators",
    businessImpact: "medium",
    likelyDriver: "Documentation gap in KnowledgeV8 regarding recent FIDO2 enterprise rollout.",
    recommendation: "Publish pre-drafted Knowledge Article 'Configuring Hardware MFA & FIDO2 Keys' to Zendesk Guide.",
    recommendedOperation: "knowledge.publish",
    actionPayload: {
      title: "Configuring Hardware MFA & FIDO2 Keys",
      content: "Complete step-by-step procedure for enrolling security keys...",
    },
    status: "new",
    createdAt: "2026-08-26T01:15:00Z",
  },
  {
    id: "INS-303",
    tenantId: "tenant_default",
    title: "43 external Zendesk tickets identified as stale (safe to close)",
    finding: "Tickets marked pending customer response for >14 days with no reopen activity.",
    evidence: [
      "43 tickets in Zendesk 'Pending' state since August 10th",
      "Zero customer messages received following resolution confirmation",
      "Closing these will improve backlog metric by 18%",
    ],
    confidence: 0.98,
    affectedSegment: "All customer tiers",
    businessImpact: "low",
    likelyDriver: "Human agents leaving tickets in pending status instead of resolving.",
    recommendation: "Run Stale Work Sweeper to auto-close 43 dormant tickets with automated satisfaction survey.",
    recommendedOperation: "zendesk.ticket.close",
    status: "reviewed",
    createdAt: "2026-08-25T18:00:00Z",
  },
];

export const INITIAL_KNOWLEDGE_ARTICLES: KnowledgeArticle[] = [
  {
    id: "KB-101",
    source: "zendesk_guide",
    title: "Managing SSO and SAML 2.0 Identity Providers",
    url: "https://support.acme.com/hc/articles/360012-sso-guide",
    category: "Authentication & Security",
    usageCount: 4120,
    csatScore: 4.6,
    status: "active",
    lastUpdated: "2026-08-15",
    summary: "Comprehensive guide for setting up Okta, Azure AD, and Google Workspace SSO.",
  },
  {
    id: "KB-102",
    source: "knowledgev8",
    title: "Payment Processing & Invoicing FAQ",
    url: "https://knowledge.servicev8.internal/articles/billing-faq",
    category: "Billing & Subscriptions",
    usageCount: 2840,
    csatScore: 3.8,
    status: "stale",
    lastUpdated: "2026-04-10",
    summary: "Billing troubleshooting. Contains outdated references to Stripe legacy checkout.",
  },
  {
    id: "KB-103",
    source: "confluence",
    title: "Webhook Delivery & Retry Policy",
    url: "https://wiki.acme.com/engineering/webhooks",
    category: "Developer Platform",
    usageCount: 950,
    csatScore: 4.8,
    status: "active",
    lastUpdated: "2026-08-01",
    summary: "Technical reference for webhook headers, signatures, and exponential backoff.",
  },
];

export const INITIAL_KNOWLEDGE_GAPS: KnowledgeGap[] = [
  {
    id: "GAP-201",
    topic: "Hardware Token & FIDO2 MFA Setup",
    recurringIssueCount: 86,
    confidence: 0.94,
    sampleQueries: ["How do I register my YubiKey?", "FIDO2 security key not recognized", "Hardware MFA error 403"],
    suggestedAction: "Create new Knowledge Article with step-by-step enrollment screenshots.",
    status: "draft_proposed",
    firstDetected: "2026-08-24T10:00:00Z",
  },
  {
    id: "GAP-202",
    topic: "Automated Currency Conversion Refunds",
    recurringIssueCount: 43,
    confidence: 0.88,
    sampleQueries: ["Refund received in wrong currency", "FX fee deducted from refund", "EUR vs USD refund rate"],
    suggestedAction: "Update billing FAQ with international banking FX refund timelines.",
    status: "detected",
    firstDetected: "2026-08-25T14:30:00Z",
  },
];

export const INITIAL_KNOWLEDGE_PROPOSALS: KnowledgeProposal[] = [
  {
    id: "PROP-101",
    gapId: "GAP-201",
    targetSource: "zendesk_guide",
    title: "Configuring Hardware Security Keys (FIDO2 / YubiKey)",
    proposedContent: `# Configuring Hardware Security Keys (FIDO2 / YubiKey)

supportV8 has generated this procedure based on 86 verified successful agent resolutions.

## Prerequisites
- Supported Browser (Chrome 110+, Safari 16+, Firefox 112+)
- WebAuthn-compliant Security Key (YubiKey 5 Series, Titan Security Key)

## Step-by-Step Enrollment
1. Navigate to **Account Settings > Security > Multi-Factor Authentication**.
2. Click **Add Security Key**.
3. When prompted by your operating system, insert and touch your hardware key.
4. Name your key (e.g., 'Primary YubiKey 5C') and click **Save**.
5. Download your offline emergency backup codes.

## Troubleshooting
If key is not detected, ensure browser USB permissions are granted under *chrome://settings/content*.`,
    rationale: "Addresses 86 recurring inquiries regarding FIDO2 enrollment without requiring human agent intervention.",
    provenance: "Synthesized from 12 senior agent resolution transcripts with 100% CSAT.",
    confidence: 0.96,
    status: "pending_approval",
    createdAt: "2026-08-26T03:00:00Z",
  },
];

export const INITIAL_STALE_WORK: StaleWorkCandidate[] = [
  {
    id: "SW-01",
    issueId: "ISS-991",
    externalId: "ZD-881204",
    source: "zendesk",
    customerName: "Quantum Dynamics",
    daysInactive: 16,
    reason: "no_customer_reply",
    confidence: 0.97,
    recommendedAction: "close",
    suggestedNote: "Ticket auto-closed after 16 days of customer inactivity following resolution verification.",
    status: "detected",
  },
  {
    id: "SW-02",
    issueId: "ISS-992",
    externalId: "ZD-881330",
    source: "zendesk",
    customerName: "Starlight Media",
    daysInactive: 19,
    reason: "resolved_not_closed",
    confidence: 0.99,
    recommendedAction: "close",
    suggestedNote: "Closing ticket: Customer confirmed resolution via email on Aug 7.",
    status: "detected",
  },
  {
    id: "SW-03",
    issueId: "ISS-993",
    externalId: "IC-550102",
    source: "intercom",
    customerName: "Vertex AI Labs",
    daysInactive: 22,
    reason: "duplicate_of_problem",
    confidence: 0.91,
    recommendedAction: "link_to_problem",
    suggestedNote: "Link to Problem PRB-210 (Historical) and mark superseded.",
    status: "reviewed",
  },
];

export const INITIAL_POLICY: SupportPolicy = {
  tenantId: "tenant_default",
  operatingMode: "autonomous",
  autonomyThreshold: "medium", // 'read' | 'low' | 'medium' | 'high' | 'critical'
  confidenceMin: 0.85,
  sentimentEscalationEnabled: true,
  sentimentThreshold: "angry",
  autoProblemLinkThreshold: 0.90,
  staleWorkAutoCloseDays: 14,
  proactiveCommsApprovalRequired: true,
  retentionRawContextHours: 24,
  retentionDerivedMonths: 24,
};

export const INITIAL_OVERVIEW_METRICS: OverviewMetrics = {
  csat: 91.4,
  csatChange: -2.3,
  issueVolume: 1842,
  issueVolumeChange: +14.8,
  activeProblems: 3,
  varrRate: 74.8,
  businessExposure: 183000,
  needsAttention: [
    {
      id: "na_1",
      severity: "critical",
      title: "Checkout 504 Gateway Timeouts",
      description: "187 customers affected across Zendesk and Intercom. Estimated $126K revenue exposure.",
      impactText: "CRITICAL REVENUE AT RISK ($126K)",
      actionText: "Investigate Problem",
      targetTab: "problems",
      targetId: "PRB-218",
    },
    {
      id: "na_2",
      severity: "warning",
      title: "Billing CSAT Deterioration (94% -> 82%)",
      description: "AI refund refusals causing elevated ticket re-opens in self-serve segment.",
      impactText: "CSAT IMPACT (-12% DECLINE)",
      actionText: "Review Insight",
      targetTab: "insights",
      targetId: "INS-301",
    },
    {
      id: "na_3",
      severity: "knowledge",
      title: "Surge in FIDO2 MFA Inquiries",
      description: "86 new tickets opened. Proposed Knowledge Article ready for one-click publishing.",
      impactText: "KNOWLEDGE GAP DETECTED",
      actionText: "Review KB Proposal",
      targetTab: "knowledge",
      targetId: "PROP-101",
    },
  ],
  aiDiscovered: [
    {
      id: "ad_1",
      type: "problem",
      title: "3 Emerging Problems Detected",
      description: "Cross-channel clustering grouped 312 recent contacts into 3 systemic incidents.",
      confidence: 0.94,
      actionText: "View Correlation Matrix",
      targetTab: "problems",
    },
    {
      id: "ad_2",
      type: "gap",
      title: "2 Critical Knowledge Gaps",
      description: "Identified documentation deficits in Hardware MFA setup and currency refunds.",
      confidence: 0.95,
      actionText: "Inspect Knowledge Radar",
      targetTab: "knowledge",
    },
    {
      id: "ad_3",
      type: "stale",
      title: "43 Stale Tickets Safe to Close",
      description: "Dormant external helpdesk tickets ready for automated sweep.",
      confidence: 0.98,
      actionText: "Run Work Sweep",
      targetTab: "stale_work",
    },
  ],
  recentActivity: [
    {
      id: "act_1",
      timestamp: "Just now",
      type: "action_executed",
      description: "Action Gateway executed 'zendesk.ticket.add_tag' on ZD-884233 [autonomous]",
      actor: "Support AI Employee",
      badgeColor: "emerald",
    },
    {
      id: "act_2",
      timestamp: "4 mins ago",
      type: "problem_detected",
      description: "Problem PRB-218 correlated 187 issues ($126K exposure calculated)",
      actor: "Problem Engine",
      badgeColor: "rose",
    },
    {
      id: "act_3",
      timestamp: "12 mins ago",
      type: "proactive_sent",
      description: "Proactive status notification dispatched to 64 Okta SSO users",
      actor: "Proactive Comms Hub",
      badgeColor: "indigo",
    },
    {
      id: "act_4",
      timestamp: "28 mins ago",
      type: "kb_proposed",
      description: "Drafted proposed update: 'Configuring Hardware Security Keys (FIDO2)'",
      actor: "Knowledge Employee",
      badgeColor: "cyan",
    },
  ],
  aiWorkforce: [
    {
      id: "emp_1",
      name: "Triage & Resolution Employee",
      role: "Tier 1 Customer Support AI",
      status: "active",
      assignedCount: 142,
      csat: 94.2,
      varr: 82.5,
      avatar: "🤖",
    },
    {
      id: "emp_2",
      name: "Incident Correlation Employee",
      role: "Problem & Business Impact Analyst",
      status: "active",
      assignedCount: 38,
      csat: 96.0,
      varr: 91.0,
      avatar: "🧠",
    },
    {
      id: "emp_3",
      name: "Knowledge Refresh Employee",
      role: "Continuous Knowledge Improvement",
      status: "reviewing",
      assignedCount: 19,
      csat: 92.8,
      varr: 78.0,
      avatar: "📚",
    },
  ],
};

/**
 * In-Memory Store Singleton
 */
class SupportDatabase {
  public tenant: TenantConfig = { ...DEFAULT_TENANT };
  public sources: SourceConnector[] = [...INITIAL_SOURCES];
  public problems: Problem[] = [...INITIAL_PROBLEMS];
  public issues: Issue[] = [...INITIAL_ISSUES];
  public insights: Insight[] = [...INITIAL_INSIGHTS];
  public articles: KnowledgeArticle[] = [...INITIAL_KNOWLEDGE_ARTICLES];
  public gaps: KnowledgeGap[] = [...INITIAL_KNOWLEDGE_GAPS];
  public proposals: KnowledgeProposal[] = [...INITIAL_KNOWLEDGE_PROPOSALS];
  public staleWork: StaleWorkCandidate[] = [...INITIAL_STALE_WORK];
  public policy: SupportPolicy = { ...INITIAL_POLICY };

  public documents: KnowledgeDocument[] = [
    {
      id: "doc_s3_001",
      tenantId: "tenant_default",
      filename: "SAML_Okta_Setup_Guide_v2.md",
      fileType: "md",
      fileSizeBytes: 14320,
      s3Key: "tenant_default/kb/1787720000_SAML_Okta_Setup_Guide_v2.md",
      s3Url: "https://supportv8-kb-documents.s3.amazonaws.com/tenant_default/kb/1787720000_SAML_Okta_Setup_Guide_v2.md",
      category: "auth_sso",
      title: "Okta SAML 2.0 Integration & Troubleshooting Guide",
      chunkCount: 8,
      status: "indexed",
      uploadedAt: "2026-08-25T14:20:00.000Z",
      summary: "Comprehensive guide for configuring Okta SSO, entity IDs, certificates, and clock skew resolution.",
    },
    {
      id: "doc_s3_002",
      tenantId: "tenant_default",
      filename: "Checkout_Payment_Gateway_Failures_Runbook.pdf",
      fileType: "pdf",
      fileSizeBytes: 48200,
      s3Key: "tenant_default/kb/1787720100_Checkout_Payment_Gateway_Failures_Runbook.pdf",
      s3Url: "https://supportv8-kb-documents.s3.amazonaws.com/tenant_default/kb/1787720100_Checkout_Payment_Gateway_Failures_Runbook.pdf",
      category: "checkout_failure",
      title: "Checkout 504 Gateway Timeout Runbook",
      chunkCount: 14,
      status: "indexed",
      uploadedAt: "2026-08-25T18:45:00.000Z",
      summary: "Diagnostic runbook for payment gateway timeouts, database connection pooling, and circuit breaker recovery.",
    },
  ];
  public documentChunks: KnowledgeDocumentChunk[] = [];

  public webSources: KnowledgeWebSource[] = [
    {
      id: "src_web_001",
      tenantId: "tenant_default",
      url: "https://docs.acme.com/identity/sso-saml",
      title: "Acme SSO & SAML Identity Portal Docs",
      category: "auth_sso",
      crawlDepth: 1,
      pageCount: 3,
      chunkCount: 12,
      status: "indexed",
      lastCrawledAt: "2026-08-25T16:00:00.000Z",
      s3SnapshotUrl: "https://supportv8-kb-documents.s3.amazonaws.com/tenant_default/kb/web_docs_acme_com_1787720000.md",
      summary: "Official customer documentation on configuring federated SAML SSO, attribute mappings, and certificates.",
    },
    {
      id: "src_web_002",
      tenantId: "tenant_default",
      url: "https://status.acme.com/history",
      title: "Acme Cloud Infrastructure Status & Incident History",
      category: "infrastructure",
      crawlDepth: 1,
      pageCount: 1,
      chunkCount: 6,
      status: "indexed",
      lastCrawledAt: "2026-08-26T00:30:00.000Z",
      s3SnapshotUrl: "https://supportv8-kb-documents.s3.amazonaws.com/tenant_default/kb/web_status_acme_com_1787720500.md",
      summary: "System availability history, planned maintenance windows, and regional latency notices for EMEA and US-East.",
    },
  ];

  public getOverviewMetrics(): OverviewMetrics {
    return {
      ...INITIAL_OVERVIEW_METRICS,
      activeProblems: this.problems.filter((p) => p.status !== "resolved").length,
      businessExposure: this.problems
        .filter((p) => p.status !== "resolved")
        .reduce((sum, p) => sum + p.estimatedRevenueExposure, 0),
    };
  }
}

export const db = new SupportDatabase();
