CREATE UNIQUE INDEX IF NOT EXISTS uq_runtime_support_workspace_registration_identity ON supportv8.runtime_support_workspaces(installation_id,operation_id,account_id,registry_tenant_id,vertical_id,native_tenant_id);
CREATE TABLE IF NOT EXISTS supportv8.managed_support_registration_jobs (
 installation_id varchar(128) PRIMARY KEY REFERENCES supportv8.runtime_support_workspaces(installation_id), acquisition_id varchar(128) NOT NULL,
 account_id varchar(128) NOT NULL, registry_tenant_id varchar(128) NOT NULL, vertical_id varchar(32) NOT NULL CHECK(vertical_id='runtime'),
 native_workspace_id varchar(64) NOT NULL REFERENCES supportv8.tenants(id), connection_id uuid,
 state varchar(32) NOT NULL DEFAULT 'pending' CHECK(state IN('pending','connected','ready','conflict')), attempt_count integer NOT NULL DEFAULT 0 CHECK(attempt_count>=0),
 next_attempt_at timestamptz NOT NULL DEFAULT now(), lease_owner varchar(128), lease_expires_at timestamptz, last_error_code varchar(64),
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(acquisition_id), UNIQUE(native_workspace_id),
 FOREIGN KEY(installation_id,acquisition_id,account_id,registry_tenant_id,vertical_id,native_workspace_id)
  REFERENCES supportv8.runtime_support_workspaces(installation_id,operation_id,account_id,registry_tenant_id,vertical_id,native_tenant_id) DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX idx_managed_support_registration_due ON supportv8.managed_support_registration_jobs(next_attempt_at,account_id) WHERE state IN('pending','connected');
CREATE FUNCTION supportv8.protect_managed_support_registration_job() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF ROW(NEW.installation_id,NEW.acquisition_id,NEW.account_id,NEW.registry_tenant_id,NEW.vertical_id,NEW.native_workspace_id) IS DISTINCT FROM ROW(OLD.installation_id,OLD.acquisition_id,OLD.account_id,OLD.registry_tenant_id,OLD.vertical_id,OLD.native_workspace_id) THEN RAISE EXCEPTION 'managed Support registration identity is immutable' USING ERRCODE='23514'; END IF;
 IF OLD.connection_id IS NOT NULL AND NEW.connection_id IS DISTINCT FROM OLD.connection_id THEN RAISE EXCEPTION 'managed Support connection identity is immutable' USING ERRCODE='23514'; END IF;
 IF OLD.state IN('ready','conflict') AND NEW.state<>OLD.state THEN RAISE EXCEPTION 'managed Support registration terminal state is immutable' USING ERRCODE='23514'; END IF; RETURN NEW; END $$;
CREATE TRIGGER protect_managed_support_registration_job BEFORE UPDATE ON supportv8.managed_support_registration_jobs FOR EACH ROW EXECUTE FUNCTION supportv8.protect_managed_support_registration_job();
CREATE FUNCTION supportv8.deny_managed_support_registration_delete() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'managed Support registration jobs are immutable' USING ERRCODE='23514'; END $$;
CREATE TRIGGER deny_managed_support_registration_delete BEFORE DELETE ON supportv8.managed_support_registration_jobs FOR EACH ROW EXECUTE FUNCTION supportv8.deny_managed_support_registration_delete();
ALTER TABLE supportv8.managed_support_registration_jobs ENABLE ROW LEVEL SECURITY; ALTER TABLE supportv8.managed_support_registration_jobs FORCE ROW LEVEL SECURITY;
CREATE POLICY managed_support_registration_exact_scope ON supportv8.managed_support_registration_jobs FOR INSERT WITH CHECK(native_workspace_id=current_setting('app.current_tenant_id',true) AND account_id=current_setting('app.current_account_id',true) AND registry_tenant_id=current_setting('app.current_registry_tenant_id',true));
CREATE POLICY managed_support_registration_scope_read ON supportv8.managed_support_registration_jobs FOR SELECT USING(native_workspace_id=current_setting('app.current_tenant_id',true) AND account_id=current_setting('app.current_account_id',true) AND registry_tenant_id=current_setting('app.current_registry_tenant_id',true));
INSERT INTO supportv8.managed_support_registration_jobs(installation_id,acquisition_id,account_id,registry_tenant_id,vertical_id,native_workspace_id)
 SELECT installation_id,operation_id,account_id,registry_tenant_id,vertical_id,native_tenant_id FROM supportv8.runtime_support_workspaces WHERE state='workspace_created' AND deleted_at IS NULL ON CONFLICT(installation_id) DO NOTHING;
CREATE FUNCTION supportv8.claim_managed_support_registration_jobs(worker varchar,claim_limit integer) RETURNS SETOF supportv8.managed_support_registration_jobs LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog,supportv8 AS $$
 WITH candidates AS(SELECT installation_id FROM(SELECT installation_id,next_attempt_at,account_id,row_number()OVER(PARTITION BY account_id ORDER BY next_attempt_at,installation_id) account_rank FROM supportv8.managed_support_registration_jobs WHERE state IN('pending','connected') AND next_attempt_at<=now() AND(lease_expires_at IS NULL OR lease_expires_at<now()))ranked WHERE account_rank<=2 ORDER BY next_attempt_at,account_id,installation_id LIMIT greatest(1,least(claim_limit,64))),locked AS(SELECT j.installation_id FROM supportv8.managed_support_registration_jobs j JOIN candidates c USING(installation_id) WHERE j.state IN('pending','connected') AND j.next_attempt_at<=now() AND(j.lease_expires_at IS NULL OR j.lease_expires_at<now()) FOR UPDATE OF j SKIP LOCKED)
 UPDATE supportv8.managed_support_registration_jobs j SET lease_owner=worker,lease_expires_at=now()+interval '2 minutes',updated_at=now() FROM locked WHERE j.installation_id=locked.installation_id AND j.state IN('pending','connected') AND j.next_attempt_at<=now() AND(j.lease_expires_at IS NULL OR j.lease_expires_at<now()) RETURNING j.* $$;
CREATE FUNCTION supportv8.finish_managed_support_registration_job(worker varchar,target_installation varchar,target_state varchar,target_connection uuid,error_code varchar,retry_at timestamptz) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,supportv8 AS $$ BEGIN
 UPDATE supportv8.managed_support_registration_jobs SET state=target_state,connection_id=COALESCE(target_connection,connection_id),attempt_count=attempt_count+1,next_attempt_at=COALESCE(retry_at,now()),last_error_code=error_code,lease_owner=NULL,lease_expires_at=NULL,updated_at=now() WHERE installation_id=target_installation AND lease_owner=worker AND lease_expires_at>=now();
 IF NOT FOUND THEN RAISE EXCEPTION 'managed Support registration lease lost' USING ERRCODE='40001'; END IF; END $$;
REVOKE ALL ON FUNCTION supportv8.claim_managed_support_registration_jobs(varchar,integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION supportv8.finish_managed_support_registration_job(varchar,varchar,varchar,uuid,varchar,timestamptz) FROM PUBLIC;
COMMENT ON FUNCTION supportv8.claim_managed_support_registration_jobs(varchar,integer) IS 'Bounded lifecycle metadata worker; SECURITY DEFINER intentionally crosses forced RLS after EXECUTE is revoked from PUBLIC.';
COMMENT ON FUNCTION supportv8.finish_managed_support_registration_job(varchar,varchar,varchar,uuid,varchar,timestamptz) IS 'Lease-bound lifecycle metadata update; SECURITY DEFINER intentionally crosses forced RLS after EXECUTE is revoked from PUBLIC.';
DO $grants$ BEGIN IF to_regrole('supportv8_app') IS NOT NULL THEN EXECUTE 'GRANT SELECT,INSERT ON supportv8.managed_support_registration_jobs TO supportv8_app';EXECUTE 'GRANT EXECUTE ON FUNCTION supportv8.claim_managed_support_registration_jobs(varchar,integer) TO supportv8_app';EXECUTE 'GRANT EXECUTE ON FUNCTION supportv8.finish_managed_support_registration_job(varchar,varchar,varchar,uuid,varchar,timestamptz) TO supportv8_app';END IF;END $grants$;
