/**
 * Adapter converting a DeclarativeScenario into an executable Engine for runAgent().
 */

import type { AgentResolution, Engine, EngineContext, OperationProposal } from "../engine/contract";
import type { DeclarativeScenario } from "./schema";

export type ComputeHandler = (
  ctx: EngineContext,
  scenario: DeclarativeScenario,
) => Promise<Record<string, unknown>[] | Record<string, unknown>>;

/**
 * Creates a runnable Engine from a DeclarativeScenario manifest.
 *
 * @param scenario The validated declarative scenario definition.
 * @param computeHandler Function providing the deterministic compute dataset.
 */
export function declarativeScenarioToEngine(
  scenario: DeclarativeScenario,
  computeHandler?: ComputeHandler,
): Engine {
  return async (ctx: EngineContext): Promise<AgentResolution> => {
    // 1. Execute deterministic compute
    let computeResult: Record<string, unknown>[] | Record<string, unknown> = [];
    if (computeHandler) {
      computeResult = await computeHandler(ctx, scenario);
    } else if (ctx.tuning["dataset"] && Array.isArray(ctx.tuning["dataset"])) {
      computeResult = ctx.tuning["dataset"] as Record<string, unknown>[];
    } else if (ctx.tuning["data"] && isRecord(ctx.tuning["data"])) {
      computeResult = ctx.tuning["data"];
    }

    const items = Array.isArray(computeResult) ? computeResult : [computeResult];
    const proposals: OperationProposal[] = [];
    const actionsTaken: string[] = [];

    // 2. Generate proposals from declarative mapping
    for (const item of items) {
      if (!isRecord(item) || Object.keys(item).length === 0) continue;

      for (const pConfig of scenario.proposals) {
        // Map payload fields
        const input: Record<string, unknown> = {};
        if (pConfig.payloadMapping) {
          for (const [targetKey, sourceKey] of Object.entries(pConfig.payloadMapping)) {
            input[targetKey] = item[sourceKey] ?? item[targetKey];
          }
        } else {
          Object.assign(input, item);
        }

        // Generate idempotency key
        const idempotencyKey = renderTemplate(pConfig.idempotencyPattern, {
          ...item,
          tenant: ctx.tenant.tenantDomain,
          scenario: scenario.id,
        });

        proposals.push({
          operationId: pConfig.operation,
          input,
          reason: `Auto-generated by scenario ${scenario.name} (${scenario.id})`,
          idempotencyKey,
        });

        actionsTaken.push(`PROPOSED:${pConfig.operation}:${idempotencyKey}`);
      }
    }

    // 3. Single metered narration call (if configured)
    let recommendation: string | undefined;
    if (scenario.narration?.systemPrompt) {
      const summaryPrompt = `${scenario.narration.systemPrompt}\n\nScenario Data: ${JSON.stringify(items)}\nProposals count: ${proposals.length}`;
      const narrative = await ctx.narrate(summaryPrompt);
      if (narrative) {
        recommendation = narrative;
      }
    } else if (proposals.length > 0) {
      recommendation = `Scenario ${scenario.name} executed: generated ${proposals.length} proposal(s).`;
    }

    return {
      executed: true,
      ...(recommendation ? { recommendation } : {}),
      actionsTaken: actionsTaken.length > 0 ? actionsTaken : [`EVALUATED:${scenario.id}:0_proposals`],
      proposals,
    };
  };
}

function renderTemplate(pattern: string, vars: Record<string, unknown>): string {
  let result = pattern;
  for (const [k, v] of Object.entries(vars)) {
    result = result.replaceAll(`{${k}}`, String(v ?? ""));
  }
  return result;
}

function isRecord(val: unknown): val is Record<string, unknown> {
  return Boolean(val) && typeof val === "object" && !Array.isArray(val);
}
